apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledemo-deployment
  labels:
    app: hellodemo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellodemo
      bb: web
  template:
    metadata:
      labels:
        bb: web
        app: hellodemo
    spec:
      containers:
      - name: hellodemo
        image: docker.io/igorbraga/hellocloudyaml:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
          protocol: TCP
